name: Dusk

on: [push]

jobs:
  dusk:
    name: Dusk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS medialibrary_test;'

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          yarn
          yarn run dev

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Dusk
        run: |
          php artisan serve & php artisan dusk
        env:
          APP_URL: "http://127.0.0.1:8000"
          DB_PASSWORD: "root"
          DB_DATABASE: "medialibrary_test"

      - name: Upload dusk console
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: dusk-console
          path: tests/Browser/console

      - name: Upload dusk screenshots
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: dusk-console
          path: tests/Browser/screenshots
