name: Dusk

on: [push]

jobs:
  dusk:
    name: Dusk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS medialibrary_test;'

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Prepare Laravel Application
        run: |
          cp phpunit.dusk.github.xml phpunit.dusk.xml
          php artisan key:generate
          php artisan dusk:chrome-driver 72

      - name: Run Dusk
        run: |
          php artisan serve & php artisan dusk
        env:
           DB_PASSWORD: root
           DB_CONNECTION: mysql
           DB_DATABASE: medialibrary_test
           DB_HOST: 127.0.0.1

      - name: Upload dusk console
        uses: actions/upload-artifact@v1
        with:
          name: dusk-console
          path: tests/Browser/console

      - name: Upload dusk screenshots
        uses: actions/upload-artifact@v1
        with:
          name: dusk-console
          path: tests/Browser/screenshots
